### ISSUE TITLE
Please consider adding a current pdf copy of the guide to the repository

### ISSUE THREAD

**Issue by anaaktge** [CTSRD-CHERI/cheri-c-programming#5]
I'm very glad to see the guide come out. It would be extremely handy if there was a pdf copy of the programming guide present in the repo. I understand from nwf that other documents in the cheri family are tied to build scripts that update the pdf when tex changes are check in. Perhaps that could be re-used it? 

tex is not very common outside of academia, at least on this side of the pond. Interested parties may uncomfortable or unwilling to install software and compile code just to check out documentation on your project.

It also doesn't send the most welcoming of messages to potential new contributors.

**Comment by jrtc27** [comment]
See https://github.com/CTSRD-CHERI/cheri-c-programming/actions. Every push is built by CI and the result published, which is a far better solution than committing documents to the repo (an unfortunate but understandable anti-pattern). I have added a pointer to the README.

**Comment by arichardson** [comment]
It seems like those PDFs are not dowloadable if you are not logged in to github.

**Comment by jrtc27** [comment]
_sigh_ that's an obnoxious decision on GitHub's part to disable the download link. I still don't believe PDFs belong committed to a Git repo though, conflicts are a nuisance and it wastes space storing the history of the produced binary artefact. I don't think requiring people to log in to GitHub is much to ask, and there will eventually be a published copy on the website.
